version: "3"
services:
  creditcontroller:
    container_name: creditcontroller
    build: "./credit"
    ports:
      - "8090:8090"
    depends_on:
      - postgresdb
      - productcontroller
      - customercontroller

  customercontroller:
    container_name: customercontroller
    build: "./customer"
    ports:
      - "8091:8091"
    depends_on:
      - postgresdb
      - productcontroller

  productcontroller:
    container_name: productcontroller
    build: "./product"
    ports:
      - "8092:8092"
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    user: postgres
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    expose:
      - "5432"
    ports:
    - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
