version: "3"
services:
  creditcontroller:
    build: "./credit"
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
      - productcontroller
      - customercontroller
    links:
      - postgresdb
      - customercontroller
      - productcontroller
    network_mode: bridge
  customercontroller:
    build: "./customer"
    ports:
      - "8081:8081"
    depends_on:
      - postgresdb
    links:
      - postgresdb
    network_mode: bridge
  productcontroller:
    build: "./product"
    ports:
      - "8082:8082"
    depends_on:
      - postgresdb
    links:
      - postgresdb
    network_mode: bridge

  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    network_mode: bridge
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    expose:
      - "5432"
    ports:
    - "5432:5432"
